server:
<<<<<<< HEAD
  port: 8080
  servlet:
    context-path: /demo
=======
  port: 58083 #netstat -ano|findstr 58083 查看8080端口被谁占用   taskkill /f /t /im 6036
  servlet:
    context-path: /api
>>>>>>> dev

  #com.mysql.jdbc.Driver过时
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf655z4n9sg2kmrz93o.mysql.rds.aliyuncs.com:3306/_10chen_mysql
    username: _10chen_mysql
    password: _10chen_mysql


    # Hikari 数据源专用配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    # JPA 相关配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

<<<<<<< HEAD
=======
logging:
  file:
    path: ../db/logs
>>>>>>> dev
